AllCops:
  Exclude:
    - "vendor/**/*"
    - "node_modules/**/*"
    - "test/scratch/**/*"
  TargetRubyVersion: 2.6
  NewCops: disable
  SuggestExtensions: false

require:
  - rubocop-performance

Security:
  Enabled: true

Performance:
  Enabled: true

Layout:
  Enabled: false

Metrics:
  Enabled: false

Style:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
